"""
ReflectionState answers:

    Did the previous action make progress?
    Is the user's goal completed?
    Does the agent need to replan?
    Did something fail?
    Is the agent stuck?
"""

from dataclasses import dataclass


@dataclass
class ReflectionState:
    """
    Stores the latest reflection generated by the Reflection node.

    This state is persistent and is used by the Runtime and Planner
    to determine what should happen next.
    """

    # ---------------------------------------------------------
    # Progress
    # ---------------------------------------------------------

    progress_made: bool = False

    goal_completed: bool = False

    # ---------------------------------------------------------
    # Decision
    # ---------------------------------------------------------

    needs_replanning: bool = False

    failure_detected: bool = False

    agent_stuck: bool = False

    # ---------------------------------------------------------
    # Reflection
    # ---------------------------------------------------------

    confidence: float = 0.0

    verified: bool = False

    reason: str = ""

    summary: str = ""