from src.agent.observer.models.observation import Observation


class ObservationValidator:
    """
    Validates an Observation generated by the Observer LLM.

    This validator only checks structural and logical consistency.
    It does NOT perform reasoning.
    """

    def validate(
        self,
        observation: Observation,
    ) -> None:

        # ---------------------------------------------------------
        # Confidence
        # ---------------------------------------------------------

        if not (0.0 <= observation.confidence <= 1.0):

            raise ValueError(
                "Observation confidence must be between 0.0 and 1.0."
            )

        # ---------------------------------------------------------
        # Summary
        # ---------------------------------------------------------

        if not observation.summary.strip():

            raise ValueError(
                "Observation summary cannot be empty."
            )

        # ---------------------------------------------------------
        # Actual Outcome
        # ---------------------------------------------------------

        if not observation.actual_outcome.strip():

            raise ValueError(
                "Actual outcome cannot be empty."
            )

        # ---------------------------------------------------------
        # Expected Outcome
        # ---------------------------------------------------------

        if not observation.expected_outcome.strip():

            raise ValueError(
                "Expected outcome cannot be empty."
            )

        # ---------------------------------------------------------
        # Goal Achievement
        # ---------------------------------------------------------

        if observation.goal_achieved and not observation.success:

            raise ValueError(
                "Goal cannot be achieved if execution failed."
            )

        # ---------------------------------------------------------
        # Mismatch
        # ---------------------------------------------------------

        if (
            observation.mismatch_detected
            and not observation.mismatch_reason
        ):

            raise ValueError(
                "Mismatch reason is required when mismatch_detected=True."
            )

        if (
            not observation.mismatch_detected
            and observation.mismatch_reason
        ):

            raise ValueError(
                "Mismatch reason must be empty when mismatch_detected=False."
            )

        # ---------------------------------------------------------
        # World Updates
        # ---------------------------------------------------------

        if not isinstance(
            observation.world_updates,
            dict,
        ):

            raise ValueError(
                "world_updates must be a dictionary."
            )