from typing import Any

from pydantic import BaseModel, Field


class Observation(BaseModel):
    """
    Structured understanding of what happened after executing
    a planner action.

    Generated by the Observer LLM.
    """

    success: bool = Field(
        description="Whether the tool execution itself succeeded."
    )

    goal_achieved: bool = Field(
        description="Whether the planner's expected outcome was achieved."
    )

    expected_outcome: str = Field(
        description="Expected outcome provided by the Planner."
    )

    actual_outcome: str = Field(
        description="Actual outcome observed from the tool execution."
    )

    mismatch_detected: bool = Field(
        description="True if the actual outcome differs from the expected outcome."
    )

    mismatch_reason: str | None = Field(
        default=None,
        description="Reason describing why the mismatch occurred."
    )

    world_updates: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Facts that should be merged into the WorldState. "
            "Example: browser url, page title, created file, network state."
        ),
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score assigned by the Observer."
    )

    summary: str = Field(
        description="Short summary of what happened."
    )