from src.agent.models.action import Action
from src.agent.tools.registry import ToolRegistry


class ActionValidator:
    """
    Validates actions generated by the planner.
    """

    def __init__(
        self,
        tool_registry: ToolRegistry,
    ) -> None:

        self._tool_registry = tool_registry

    def validate(
        self,
        action: Action,
    ) -> None:
        """
        Validate planner action.

        Raises:
            ValueError if invalid.
        """

        if not action.tool:
            raise ValueError("Tool cannot be empty.")

        if not action.action:
            raise ValueError("Action cannot be empty.")

        tool = self._tool_registry.get(action.tool)

        if tool is None:
            raise ValueError(
                f"Unknown tool '{action.tool}'."
            )

        schema = self._tool_registry.get_schema(
            action.tool
        )

        actions = {
            a["name"]
            for a in schema["actions"]
        }

        if action.action not in actions:
            raise ValueError(
                f"Tool '{action.tool}' "
                f"does not support "
                f"'{action.action}'."
            )

        # Argument validation can be added later.