from src.agent.prompts.builder.base_prompt_builder import BasePromptBuilder
from src.agent.prompts.templates.reasoner_template import SYSTEM_PROMPT
from src.agent.state.agent_state import AgentState


class ReasonerPromptBuilder(BasePromptBuilder):

    def __init__(
        self,
        conversation_formatter,
        planning_formatter,
        execution_formatter,
        world_formatter,
        reflection_formatter,
        recovery_formatter,
        reasoner_formatter,
    ) -> None:

        self.conversation_formatter = conversation_formatter
        self.planning_formatter = planning_formatter
        self.execution_formatter = execution_formatter
        self.world_formatter = world_formatter
        self.reflection_formatter = reflection_formatter
        self.recovery_formatter = recovery_formatter
        self.reasoner_formatter = reasoner_formatter

    def build(
        self,
        state: AgentState,
    ) -> str:

        sections = [

            SYSTEM_PROMPT,

            f"""
============================================================
USER GOAL
============================================================

{state.goal.user_goal}
""",

            f"""
============================================================
PREVIOUS REASONING
============================================================

This is your previous understanding of the task.

Use it to maintain continuity between reasoning cycles.

{self.reasoner_formatter.format(state.reasoner)}
""",

            f"""
============================================================
CURRENT PLAN
============================================================

This is the last plan generated by the Planner.

Use it to understand what the agent attempted.

{self.planning_formatter.format(state.planning)}
""",

            f"""
============================================================
LAST EXECUTION
============================================================

This is the result of the previously executed action.

{self.execution_formatter.format(state.execution)}
""",

            f"""
============================================================
WORLD STATE
============================================================

This is the current understanding of the environment.

Treat the World State as the source of truth.

Use it to determine what has already been completed
and what still remains.

{self.world_formatter.format(state.world)}
""",

            f"""
============================================================
LAST REFLECTION
============================================================

Reflection summarizes the progress made during the
previous iteration.

Use it to understand whether the goal is advancing.

{self.reflection_formatter.format(state.reflection)}
""",

            f"""
============================================================
LAST RECOVERY
============================================================

Recovery summarizes the previous runtime decision.

Use it to identify failures, retries,
or strategy changes.

{self.recovery_formatter.format(state.recovery)}
""",

            f"""
============================================================
CONVERSATION
============================================================

This is the complete conversation history.

Use it to understand the user's real objective,
constraints, clarifications, and preferences.

{self.conversation_formatter.format(state.conversation)}
""",
        ]

        return "\n\n".join(sections)